# Generated by Django 4.2.11 on 2026-04-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('policy_type', models.CharField(max_length=100)),
                ('nominee', models.CharField(max_length=100)),
                ('coverage_amount', models.CharField(max_length=50)),
            ],
        ),
    ]
